site_name: My Docs

markdown_extensions:
- attr_list
- toc
- pymdownx.arithmatex:
    generic: true

extra_javascript:
  #- script.js
  - generic.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
